<!--
Author: Matthew Rozendaal
Date: June 2, 2026
Assignment: Module 1.3 - Simple JSP Page
Purpose: Demonstrates a basic JSP page that displays a student name and the current server date/time.

Source/Citation:
- Initial draft generated with Microsoft Copilot (GPT-5.3) on June 2, 2026.
- Microsoft. (2026). Code generated by Copilot (GPT-5.3) [Large language model]. Microsoft.

Notes:
- Updated and reviewed for JSP readability and course documentation expectations.
-->
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="java.time.LocalDateTime,java.time.format.DateTimeFormatter" %>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple JSP Example</title>
</head>
<body>
    <h1>Simple JSP Page</h1>

    <%
        String studentName = "Random Person";
        LocalDateTime now = LocalDateTime.now();
        String formattedDate = now.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
    %>

    <p>Hello, <strong><%= studentName %></strong>.</p>
    <p>Current server date and time: <%= formattedDate %></p>

    <p>This page demonstrates:</p>
    <ul>
        <li>JSP directives</li>
        <li>Embedded Java scriptlet code</li>
        <li>JSP expression tags</li>
        <li>Valid HTML structure</li>
    </ul>
</body>
</html>